---
# configure
docker_user: "deploy"

docker_config:
  #  authorization-plugins: []
  #  data-root: "/var/lib/docker"
  #  dns: []
  #  dns-opts: []
  #  dns-search: []
  #  exec-opts: []
  #  exec-root: "/var/run/docker"
  #  experimental: false
  #  storage-driver: ""
  #  storage-opts: []
  #  labels: []
  live-restore: true
  #  log-driver: ""
  #  log-opts: {}
  #  mtu: 0
  #  pidfile: "/var/run/docker.pid"
  #  cluster-store: "",
  #  cluster-store-opts: {},
  #  cluster-advertise: "",
  #  max-concurrent-downloads: 3
  #  max-concurrent-uploads: 5
  #  default-shm-size: "64M"
  #  shutdown-timeout: 15
  #  debug: false
  hosts: ["fd://"]
  #  log-level: "info"
  #  tls: false
  #  tlsverify: false
  #  tlscacert: ""
  #  tlscert: ""
  #  tlskey: ""
  #  swarm-default-advertise-addr: ""
  #  api-cors-header: ""
  #  selinux-enabled: false
  #  userns-remap: ""
  #  group: ""
  #  cgroup-parent: ""
  #  default-ulimits: {}
  #  init: false
  #  init-path: "/usr/libexec/docker-init"
  #  ipv6: false
  #  iptables: true
  #  ip-forward: true
  #  ip-masq: true
  #  userland-proxy: false
  #  userland-proxy-path: "/usr/libexec/docker-proxy"
  #  ip: "0.0.0.0"
  #  bridge: ""
  #  bip: ""
  #  fixed-cidr: ""
  #  fixed-cidr-v6: ""
  #  default-gateway: ""
  #  default-gateway-v6: ""
  #  icc: true
  #  raw-logs: false
  #  registry-mirrors: []
  #  seccomp-profile: ""
  #  insecure-registries: []
  #  no-new-privileges: false
  #  default-runtime: ""
  #  oom-score-adjust: "-500"
  #  node-generic-resources: []

docker_cert_path: "~/.docker"
docker_cacert_file: ""
docker_cert_file: ""
docker_key_file: ""

docker_login_credentials: {}
#  registry: "https://index.docker.io/v1/"
#  username: ""
#  password: ""

# install
docker_state: "present"
docker_version: "20.10*"
docker_service_enabled: yes

docker_requirements:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg2
  - python3-pip
  - software-properties-common

docker_gpg_key_url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
docker_compose_url:  "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64"
docker_compose_plugins_dir: "/usr/local/lib/docker/cli-plugins"
